### ISSUE TITLE
Bug on avatar on Google Chrome

### ISSUE THREAD

**Issue by andreslucena** [AjuntamentdeBarcelona/decidim-design#141] opened 2017-02-07 07:40 UTC
#### :tophat: User Story

When I go to https://decidim-design.herokuapp.com/meeting-view/ on the proposals list, the author avatar seems broken 

![imatge](https://cloud.githubusercontent.com/assets/717367/22682045/e85d2c98-ed10-11e6-9445-d7b020d32cf1.png)

It reproduces on production 

![imatge](https://cloud.githubusercontent.com/assets/717367/22682059/f9533c90-ed10-11e6-816d-a4c3097d4c94.png)

Seems related with display: flex on .author__avatar 

#### :dart: Acceptance criteria

I should see this sections without the weird image or the padding.

**Comment by mrcasals** [comment] 2017-02-07 07:55
For debugging purposes, using Chrome v55 on Mac I see the avatar correctly:

![](https://i.imgur.com/hACttt9.png)

**Comment by mrcasals** [comment] 2017-02-07 07:58
@andreslucena since production is also broken, can you give me a link where you see this behaviour? Maybe we don't have the styles updated, although I see everything ok:

https://decidim.barcelona/processes/1/f/8/results/2585
![](https://i.imgur.com/CbNyiIg.png)

**Comment by andreslucena** [comment] 2017-02-07 08:01
Seems to be on my version of chrome (Versió 48.0.2564.109 (64-bit) on Ubuntu). 

I can see it on the URL that you share ( https://decidim.barcelona/processes/1/f/8/results/2585 )

**Comment by htmlboy** [comment] 2017-02-15 12:25
It seems to be fixed in the current Chrome version (56); the reported bug is 8 versions behind. If we can't reproduce this bug in other conditions, I suggest closing this issue. Thoughts, @josepjaume ?

**Comment by josepjaume** [comment] 2017-02-15 13:07
I would close it unless we have more complaints. Agree @andreslucena?

**Closed by josepjaume** 2017-02-15 13:07 UTC
Labels: in progress
